[rgb_matrix]
  rows = 64
  cols = 64
  chain_length = 2
  parallel = 1
  hardware_mapping = "regular"
  disable_hardware_pulsing = true
  brightness = 100

[fonts]
  folder = "../assets/fonts"
  
[fonts.aliases]
  tiny = "4x6"
  small = "6x10"
  regular = "7x13"
  bold = "7x13B"
  large = "10x20"

[data]
  ingestion = "rest_api"

[data.zmq_ipc]
  endpoint = "ipc:///tmp/led-display.sock"

[data.json_folder_watcher]
  folder = "../assets/scenes"

[data.rest_api]
  port = 8080